[-verbose
-bootclasspath
/data/user/0/com.duy.compiler.javanide/files/sdk/platforms/android-27/android.jar
-classpath
.
/storage/emulated/0/JavaNIDE/sadasdasd/app/libs/common-1.1.1.jar
/storage/emulated/0/JavaNIDE/sadasdasd/app/libs/support-annotations-27.1.1.jar
/storage/emulated/0/JavaNIDE/.cached/appcompat-v7-27.1.1/classes.jar
/storage/emulated/0/JavaNIDE/.cached/animated-vector-drawable-27.1.1/classes.jar
/storage/emulated/0/JavaNIDE/.cached/livedata-core-1.1.1/classes.jar
/storage/emulated/0/JavaNIDE/.cached/runtime-1.1.1/classes.jar
/storage/emulated/0/JavaNIDE/.cached/support-compat-27.1.1/classes.jar
/storage/emulated/0/JavaNIDE/.cached/support-core-ui-27.1.1/classes.jar
/storage/emulated/0/JavaNIDE/.cached/support-core-utils-27.1.1/classes.jar
/storage/emulated/0/JavaNIDE/.cached/support-fragment-27.1.1/classes.jar
/storage/emulated/0/JavaNIDE/.cached/support-vector-drawable-27.1.1/classes.jar
/storage/emulated/0/JavaNIDE/.cached/viewmodel-1.1.1/classes.jar
/storage/emulated/0/JavaNIDE/.cached/support-media-compat-27.1.1/classes.jar
/storage/emulated/0/JavaNIDE/.cached/support-v4-27.1.1.aar/classes.jar
/storage/emulated/0/JavaNIDE/.cached/support-fragment-27.1.1/classes.jar
-sourcepath
/storage/emulated/0/JavaNIDE/sadasdasd/app/src/main/java
/storage/emulated/0/JavaNIDE/sadasdasd/app/build/generated/source
-1.7
-target
1.7
-d
/storage/emulated/0/JavaNIDE/sadasdasd/app/build/classes
/storage/emulated/0/JavaNIDE/sadasdasd/app/src/main/java/com/example/myapplication/MainActivity.java]